# Модуль exceptions.py для работы с исключениями в Mega

## Обзор

Модуль `exceptions.py` предназначен для определения пользовательских исключений, специфичных для работы с Mega API. Эти исключения позволяют более точно обрабатывать ошибки, возникающие при взаимодействии с Mega, и предоставляют информацию о причинах сбоев.

## Подробнее

Этот модуль содержит базовый класс `MegaException`, от которого наследуются другие классы исключений. Это позволяет создать иерархию исключений, специфичных для Mega, и обеспечивает более гибкую обработку ошибок.

## Классы

### `MegaException`

**Описание**: Базовый класс для всех исключений, связанных с Mega.

**Принцип работы**:
Этот класс является родительским для всех пользовательских исключений, определённых в модуле. Он наследуется от встроенного класса `Exception` и служит основой для создания специфических исключений Mega.

### `MegaIncorrectPasswordExcetion`

**Описание**: Исключение, которое выбрасывается при вводе неверного пароля или адреса электронной почты.

**Наследует**: `MegaException`

### `MegaRequestException`

**Описание**: Исключение, которое выбрасывается при возникновении ошибки в запросе к Mega API.

**Наследует**: `MegaException`